// en, ko, zhChs, zhCht
export const interestsDict = {
  "enum-interests-festival": ["Festival", "축제", "庆典", "慶典"],
  "enumdesc-interests-festival": ["Festival", "축제", "庆典", "慶典"],
  "enum-interests-cat": ["Cat", "고양이", "猫", "貓"],
  "enumdesc-interests-cat": ["Cat", "고양이", "猫", "貓"],
  "enum-interests-dance": ["Dance", "댄스", "舞蹈", "舞蹈"],
  "enumdesc-interests-dance": ["Dance", "댄스", "舞蹈", "舞蹈"],
  "enum-interests-travel": ["Travel", "여행", "旅行", "旅行"],
  "enumdesc-interests-travel": ["Travel", "여행", "旅行", "旅行"],
  "enum-interests-instagram": ["Instagram", "인스타", "Instagram", "Instagram"],
  "enumdesc-interests-instagram": ["Instagram", "인스타", "Instagram", "Instagram"],
  "enum-interests-foreignLanguage": ["Foreign Language", "외국어", "外语", "外語"],
  "enumdesc-interests-foreignLanguage": ["Foreign Language", "외국어", "外语", "外語"],
  "enum-interests-exhibition": ["Exhibition", "전시회", "展览", "展覽"],
  "enumdesc-interests-exhibition": ["Exhibition", "전시회", "展览", "展覽"],
  "enum-interests-gardening": ["Gardening", "원예", "园艺", "園藝"],
  "enumdesc-interests-gardening": ["Gardening", "원예", "园艺", "園藝"],
  "enum-interests-surfing": ["Surfing", "서핑", "冲浪", "衝浪"],
  "enumdesc-interests-surfing": ["Surfing", "서핑", "冲浪", "衝浪"],
  "enum-interests-yoga": ["Yoga", "요가", "瑜伽", "瑜伽"],
  "enumdesc-interests-yoga": ["Yoga", "요가", "瑜伽", "瑜伽"],
  "enum-interests-jogging": ["Jogging", "조깅", "慢跑", "慢跑"],
  "enumdesc-interests-jogging": ["Jogging", "조깅", "慢跑", "慢跑"],
  "enum-interests-photography": ["Photography", "사진찍기", "摄影", "攝影"],
  "enumdesc-interests-photography": ["Photography", "사진찍기", "摄影", "攝影"],
  "enum-interests-hiking": ["Hiking", "등산", "徒步旅行", "徒步旅行"],
  "enumdesc-interests-hiking": ["Hiking", "등산", "徒步旅行", "徒步旅行"],
  "enum-interests-bornInThe90s": ["Born in the 90s", "90년대생", "90年代出生", "90年代出生"],
  "enumdesc-interests-bornInThe90s": ["Born in the 90s", "90년대생", "90年代出生", "90年代出生"],
  "enum-interests-boardGames": ["Board Games", "보드게임", "桌游", "桌遊"],
  "enumdesc-interests-boardGames": ["Board Games", "보드게임", "桌游", "桌遊"],
  "enum-interests-challengeSeeker": ["Challenge Seeker", "도전을 추구하는 편", "追求挑战", "追求挑战"],
  "enumdesc-interests-challengeSeeker": ["Challenge Seeker", "도전을 추구하는 편", "追求挑战", "追求挑战"],
  "enum-interests-reading": ["Reading", "독서", "阅读", "閱讀"],
  "enumdesc-interests-reading": ["Reading", "독서", "阅读", "閱讀"],
  "enum-interests-cooking": ["Cooking", "요리", "烹饪", "烹飪"],
  "enumdesc-interests-cooking": ["Cooking", "요리", "烹饪", "烹飪"],
  "enum-interests-walking": ["Walking", "산책", "散步", "散步"],
  "enumdesc-interests-walking": ["Walking", "산책", "散步", "散步"],
  "enum-interests-trivia": ["Trivia", "잡다한지식", "琐事", "琐事"],
  "enumdesc-interests-trivia": ["Trivia", "잡다한지식", "琐事", "琐事"],
  "enum-interests-netflix": ["Netflix", "넷플릭스", "Netflix", "Netflix"],
  "enumdesc-interests-netflix": ["Netflix", "넷플릭스", "Netflix", "Netflix"],
  "enum-interests-gourmet": ["Gourmet", "미식", "美食", "美食"],
  "enumdesc-interests-gourmet": ["Gourmet", "미식", "美食", "美食"],
  "enum-interests-camping": ["Camping", "캠핑", "露营", "露營"],
  "enumdesc-interests-camping": ["Camping", "캠핑", "露营", "露營"],
  "enum-interests-vr": ["VR", "VR", "VR", "VR"],
  "enumdesc-interests-vr": ["VR", "VR", "VR", "VR"],
  "enum-interests-exercise": ["Exercise", "운동", "运动", "運動"],
  "enumdesc-interests-exercise": ["Exercise", "운동", "运动", "運動"],
  "enum-interests-music": ["Music", "음악", "音乐", "音樂"],
  "enumdesc-interests-music": ["Music", "음악", "音乐", "音樂"],
  "enum-interests-ecoFriendly": ["Eco-Friendly", "친환경", "环保", "環保"],
  "enumdesc-interests-ecoFriendly": ["Eco-Friendly", "친환경", "环保", "環保"],
  "enum-interests-crossFit": ["CrossFit", "크로스핏", "CrossFit", "CrossFit"],
  "enumdesc-interests-crossFit": ["CrossFit", "크로스핏", "CrossFit", "CrossFit"],
  "enum-interests-wine": ["Wine", "와인", "葡萄酒", "葡萄酒"],
  "enumdesc-interests-wine": ["Wine", "와인", "葡萄酒", "葡萄酒"],
  "enum-interests-movie": ["Movie", "영화", "电影", "電影"],
  "enumdesc-interests-movie": ["Movie", "영화", "电影", "電影"],
  "enum-interests-karaoke": ["Karaoke", "노래방", "卡拉OK", "卡拉OK"],
  "enumdesc-interests-karaoke": ["Karaoke", "노래방", "卡拉OK", "卡拉OK"],
  "enum-interests-animation": ["Animation", "애니메이션", "动画", "動畫"],
  "enumdesc-interests-animation": ["Animation", "애니메이션", "动画", "動畫"],
  "enum-interests-diy": ["DIY", "DIY", "DIY", "DIY"],
  "enumdesc-interests-diy": ["DIY", "DIY", "DIY", "DIY"],
  "enum-interests-worldTour": ["World Tour", "세계일주", "环球旅行", "環球旅行"],
  "enumdesc-interests-worldTour": ["World Tour", "세계일주", "环球旅行", "環球旅行"],
  "enum-interests-writing": ["Writing", "글쓰기", "写作", "寫作"],
  "enumdesc-interests-writing": ["Writing", "글쓰기", "写作", "寫作"],
  "enum-interests-eSports": ["eSports", "E-스포츠", "电子竞技", "電子竞技"],
  "enumdesc-interests-eSports": ["eSports", "E-스포츠", "电子竞技", "電子竞技"],
  "enum-interests-brunch": ["Brunch", "브런치", "早午餐", "早午餐"],
  "enumdesc-interests-brunch": ["Brunch", "브런치", "早午餐", "早午餐"],
  "enum-interests-vegan": ["Vegan", "비건", "纯素", "純素"],
  "enumdesc-interests-vegan": ["Vegan", "비건", "纯素", "純素"],
  "enum-interests-bicycle": ["Bicycle", "자전거", "自行车", "自行車"],
  "enumdesc-interests-bicycle": ["Bicycle", "자전거", "自行车", "自行車"],
  "enum-interests-athlete": ["Athlete", "운동선수", "运动员", "運動員"],
  "enumdesc-interests-athlete": ["Athlete", "운동선수", "运动员", "運動員"],
  "enum-interests-prefersFriendConversations": [
    "Prefers Friend Conversations",
    "친구대화 선호",
    "更喜欢和朋友聊天",
    "更喜欢和朋友聊天",
  ],
  "enumdesc-interests-prefersFriendConversations": [
    "Prefers Friend Conversations",
    "친구대화 선호",
    "更喜欢和朋友聊天",
    "更喜欢和朋友聊天",
  ],
  "enum-interests-art": ["Art", "미술", "艺术", "藝術"],
  "enumdesc-interests-art": ["Art", "미술", "艺术", "藝術"],
  "enum-interests-picnic": ["Picnic", "소풍", "野餐", "野餐"],
  "enumdesc-interests-picnic": ["Picnic", "소풍", "野餐", "野餐"],
  "enum-interests-craftBeer": ["Craft Beer", "수제맥주", "精酿啤酒", "精釀啤酒"],
  "enumdesc-interests-craftBeer": ["Craft Beer", "수제맥주", "精酿啤酒", "精釀啤酒"],
  "enum-interests-bread": ["Bread", "빵", "面包", "麵包"],
  "enumdesc-interests-bread": ["Bread", "빵", "面包", "麵包"],
  "enum-interests-museum": ["Museum", "박물관", "博物馆", "博物館"],
  "enumdesc-interests-museum": ["Museum", "박물관", "博物馆", "博物館"],
  "enum-interests-pet": ["Pet", "반려동물", "宠物", "寵物"],
  "enumdesc-interests-pet": ["Pet", "반려동물", "宠物", "寵物"],
  "enum-interests-multicultural": ["Multicultural", "다문화", "多元文化", "多元文化"],
  "enumdesc-interests-multicultural": ["Multicultural", "다문화", "多元文化", "多元文化"],
  "enum-interests-comedy": ["Comedy", "개그", "喜剧", "喜劇"],
  "enumdesc-interests-comedy": ["Comedy", "개그", "喜剧", "喜劇"],
  "enum-interests-disney": ["Disney", "디즈니", "迪士尼", "迪士尼"],
  "enumdesc-interests-disney": ["Disney", "디즈니", "迪士尼", "迪士尼"],
  "enum-interests-swimming": ["Swimming", "수영", "游泳", "游泳"],
  "enumdesc-interests-swimming": ["Swimming", "수영", "游泳", "游泳"],
  "enum-interests-startup": ["Startup", "스타트업", "创业公司", "創業公司"],
  "enumdesc-interests-startup": ["Startup", "스타트업", "创业公司", "創業公司"],
  "enum-interests-christianity": ["Christianity", "기독교", "基督教", "基督教"],
  "enumdesc-interests-christianity": ["Christianity", "기독교", "基督教", "基督教"],
  "enum-interests-volunteering": ["Volunteering", "봉사활동", "志愿活动", "志願活動"],
  "enumdesc-interests-volunteering": ["Volunteering", "봉사활동", "志愿活动", "志願活動"],
  "enum-interests-dog": ["Dog", "애견", "狗", "狗"],
  "enumdesc-interests-dog": ["Dog", "애견", "狗", "狗"],
  "enum-interests-drive": ["Drive", "드라이브", "开车", "開車"],
  "enumdesc-interests-drive": ["Drive", "드라이브", "开车", "開車"],
  "enum-interests-drink": ["Drink", "술한잔", "喝一杯", "喝一杯"],
  "enumdesc-interests-drink": ["Drink", "술한잔", "喝一杯", "喝一杯"],
  "enum-interests-fishing": ["Fishing", "낚시", "钓鱼", "釣魚"],
  "enumdesc-interests-fishing": ["Fishing", "낚시", "钓鱼", "釣魚"],
  "enum-interests-outdoorActivity": ["Outdoor Activity", "야외활동", "户外活动", "戶外活動"],
  "enumdesc-interests-outdoorActivity": ["Outdoor Activity", "야외활동", "户外活动", "戶外活動"],
  "enum-interests-cafeHopping": ["Cafe Hopping", "카페탐방", "咖啡馆漫步", "咖啡館漫步"],
  "enumdesc-interests-cafeHopping": ["Cafe Hopping", "카페탐방", "咖啡馆漫步", "咖啡館漫步"],
  "enum-interests-sports": ["Sports", "스포츠", "体育", "體育"],
  "enumdesc-interests-sports": ["Sports", "스포츠", "体育", "體育"],
  "enum-interests-blog": ["Blog", "블로그", "博客", "博客"],
  "enumdesc-interests-blog": ["Blog", "블로그", "博客", "博客"],
  "enum-interests-nature": ["Nature", "자연", "自然", "自然"],
  "enumdesc-interests-nature": ["Nature", "자연", "自然", "自然"],
  "enum-interests-politics": ["Politics", "정치", "政治", "政治"],
  "enumdesc-interests-politics": ["Politics", "정치", "政治", "政治"],
  "enum-interests-neighborhoodWalk": ["Neighborhood Walk", "동네산책", "邻里散步", "鄰里散步"],
  "enumdesc-interests-neighborhoodWalk": ["Neighborhood Walk", "동네산책", "邻里散步", "鄰里散步"],
  "enum-interests-climbing": ["Climbing", "등반", "攀岩", "攀岩"],
  "enumdesc-interests-climbing": ["Climbing", "등반", "攀岩", "攀岩"],
  "enum-interests-performance": ["Performance", "공연", "表演", "表演"],
  "enumdesc-interests-performance": ["Performance", "공연", "表演", "表演"],
  "enum-interests-coffee": ["Coffee", "커피", "咖啡", "咖啡"],
  "enumdesc-interests-coffee": ["Coffee", "커피", "咖啡", "咖啡"],
  "enum-interests-car": ["Car", "자동차", "汽车", "汽車"],
  "enumdesc-interests-car": ["Car", "자동차", "汽车", "汽車"],
  "enum-interests-fashion": ["Fashion", "패션", "时尚", "時尚"],
  "enumdesc-interests-fashion": ["Fashion", "패션", "时尚", "時尚"],
  "enum-interests-olympics": ["Olympics", "올림픽", "奥林匹克", "奧林匹克"],
  "enumdesc-interests-olympics": ["Olympics", "올림픽", "奥林匹克", "奧林匹克"],
  "enum-interests-zodiac": ["Zodiac", "별자리", "星座", "星座"],
  "enumdesc-interests-zodiac": ["Zodiac", "별자리", "星座", "星座"],
  "enum-interests-vlog": ["Vlog", "브이로그", "Vlog", "Vlog"],
  "enumdesc-interests-vlog": ["Vlog", "브이로그", "Vlog", "Vlog"],
  "enum-interests-snack": ["Snack", "과자", "零食", "零食"],
  "enumdesc-interests-snack": ["Snack", "과자", "零食", "零食"],
  "enum-interests-bar": ["Bar", "바", "酒吧", "酒吧"],
  "enumdesc-interests-bar": ["Bar", "바", "酒吧", "酒吧"],
  "enum-interests-party": ["Party", "파티", "派对", "派對"],
  "enumdesc-interests-party": ["Party", "파티", "派对", "派對"],
  "enum-interests-golf": ["Golf", "골프", "高尔夫", "高爾夫"],
  "enumdesc-interests-golf": ["Golf", "골프", "高尔夫", "高爾夫"],
  "enum-interests-game": ["Game", "게임", "游戏", "遊戲"],
  "enumdesc-interests-game": ["Game", "게임", "游戏", "遊戲"],
  "enum-interests-podcast": ["Podcast", "팟캐스트", "播客", "播客"],
  "enumdesc-interests-podcast": ["Podcast", "팟캐스트", "播客", "播客"],
  "enum-interests-neighborhoodFriend": ["Neighborhood Friend", "동네친구", "邻里朋友", "鄰里朋友"],
  "enumdesc-interests-neighborhoodFriend": ["Neighborhood Friend", "동네친구", "邻里朋友", "鄰里朋友"],
  "enum-interests-tea": ["Tea", "차", "茶", "茶"],
  "enumdesc-interests-tea": ["Tea", "차", "茶", "茶"],
  "enum-interests-pcCafe": ["PC Cafe", "PC방", "PC室", "PC室"],
  "enumdesc-interests-pcCafe": ["PC Cafe", "PC방", "PC室", "PC室"],
  "enum-interests-foodTour": ["Food Tour", "맛집탐방", "美食之旅", "美食之旅"],
  "enumdesc-interests-foodTour": ["Food Tour", "맛집탐방", "美食之旅", "美食之旅"],
  "enum-interests-theater": ["Theater", "극장", "剧院", "劇院"],
  "enumdesc-interests-theater": ["Theater", "극장", "剧院", "劇院"],
  "enum-interests-chattingForFun": ["Chatting for Fun", "심심풀이 채팅", "闲聊", "閒聊"],
  "enumdesc-interests-chattingForFun": ["Chatting for Fun", "심심풀이 채팅", "闲聊", "閒聊"],
  "enum-interests-shopping": ["Shopping", "쇼핑", "购物", "購物"],
  "enumdesc-interests-shopping": ["Shopping", "쇼핑", "购物", "購物"],
  "enum-interests-origami": ["Origami", "종이접기", "折纸", "摺紙"],
  "enumdesc-interests-origami": ["Origami", "종이접기", "折纸", "摺紙"],
  "enum-interests-isfj": ["ISFJ", "ISFJ", "ISFJ", "ISFJ"],
  "enumdesc-interests-isfj": ["ISFJ", "ISFJ", "ISFJ", "ISFJ"],
  "enum-interests-intj": ["INTJ", "INTJ", "INTJ", "INTJ"],
  "enumdesc-interests-intj": ["INTJ", "INTJ", "INTJ", "INTJ"],
  "enum-interests-infj": ["INFJ", "INFJ", "INFJ", "INFJ"],
  "enumdesc-interests-infj": ["INFJ", "INFJ", "INFJ", "INFJ"],
  "enum-interests-infp": ["INFP", "INFP", "INFP", "INFP"],
  "enumdesc-interests-infp": ["INFP", "INFP", "INFP", "INFP"],
  "enum-interests-enfp": ["ENFP", "ENFP", "ENFP", "ENFP"],
  "enumdesc-interests-enfp": ["ENFP", "ENFP", "ENFP", "ENFP"],
  "enum-interests-esfp": ["ESFP", "ESFP", "ESFP", "ESFP"],
  "enumdesc-interests-esfp": ["ESFP", "ESFP", "ESFP", "ESFP"],
  "enum-interests-istp": ["ISTP", "ISTP", "ISTP", "ISTP"],
  "enumdesc-interests-istp": ["ISTP", "ISTP", "ISTP", "ISTP"],
  "enum-interests-isfp": ["ISFP", "ISFP", "ISFP", "ISFP"],
  "enumdesc-interests-isfp": ["ISFP", "ISFP", "ISFP", "ISFP"],
  "enum-interests-istj": ["ISTJ", "ISTJ", "ISTJ", "ISTJ"],
  "enumdesc-interests-istj": ["ISTJ", "ISTJ", "ISTJ", "ISTJ"],
  "enum-interests-esfj": ["ESFJ", "ESFJ", "ESFJ", "ESFJ"],
  "enumdesc-interests-esfj": ["ESFJ", "ESFJ", "ESFJ", "ESFJ"],
  "enum-interests-estp": ["ESTP", "ESTP", "ESTP", "ESTP"],
  "enumdesc-interests-estp": ["ESTP", "ESTP", "ESTP", "ESTP"],
  "enum-interests-estj": ["ESTJ", "ESTJ", "ESTJ", "ESTJ"],
  "enumdesc-interests-estj": ["ESTJ", "ESTJ", "ESTJ", "ESTJ"],
  "enum-interests-entj": ["ENTJ", "ENTJ", "ENTJ", "ENTJ"],
  "enumdesc-interests-entj": ["ENTJ", "ENTJ", "ENTJ", "ENTJ"],
  "enum-interests-entp": ["ENTP", "ENTP", "ENTP", "ENTP"],
  "enumdesc-interests-entp": ["ENTP", "ENTP", "ENTP", "ENTP"],
  "enum-interests-enfj": ["ENFJ", "ENFJ", "ENFJ", "ENFJ"],
  "enumdesc-interests-enfj": ["ENFJ", "ENFJ", "ENFJ", "ENFJ"],
  "enum-interests-intp": ["INTP", "INTP", "INTP", "INTP"],
  "enumdesc-interests-intp": ["INTP", "INTP", "INTP", "INTP"],
  "enum-interests-selfImprovement": ["Self Improvement", "자기계발", "自我提升", "自我提升"],
  "enumdesc-interests-selfImprovement": ["Self Improvement", "자기계발", "自我提升", "自我提升"],
  "enum-interests-stockInvestment": ["Stock Investment", "주식투자", "股票投资", "股票投資"],
  "enumdesc-interests-stockInvestment": ["Stock Investment", "주식투자", "股票投资", "股票投資"],
  "enum-interests-cryptocurrency": ["Cryptocurrency", "암호화폐", "加密货币", "加密貨幣"],
  "enumdesc-interests-cryptocurrency": ["Cryptocurrency", "암호화폐", "加密货币", "加密貨幣"],
  "enum-interests-catholicism": ["Catholicism", "천주교", "天主教", "天主教"],
  "enumdesc-interests-catholicism": ["Catholicism", "천주교", "天主教", "天主教"],
  "enum-interests-buddhism": ["Buddhism", "불교", "佛教", "佛教"],
  "enumdesc-interests-buddhism": ["Buddhism", "불교", "佛教", "佛教"],
  "enum-interests-atheism": ["Atheism", "무교", "无神论", "無神論"],
  "enumdesc-interests-atheism": ["Atheism", "무교", "无神论", "無神論"],
  "enum-interests-baseball": ["Baseball", "야구", "棒球", "棒球"],
  "enumdesc-interests-baseball": ["Baseball", "야구", "棒球", "棒球"],
  "enum-interests-soccer": ["Soccer", "축구", "足球", "足球"],
  "enumdesc-interests-soccer": ["Soccer", "축구", "足球", "足球"],
  "enum-interests-basketball": ["Basketball", "농구", "篮球", "籃球"],
  "enumdesc-interests-basketball": ["Basketball", "농구", "篮球", "籃球"],
  "enum-interests-skiing": ["Skiing", "스키", "滑雪", "滑雪"],
  "enumdesc-interests-skiing": ["Skiing", "스키", "滑雪", "滑雪"],
  "enum-interests-freeDiving": ["Free Diving", "프리다이빙", "自由潜水", "自由潛水"],
  "enumdesc-interests-freeDiving": ["Free Diving", "프리다이빙", "自由潜水", "自由潛水"],
  "enum-interests-scubaDiving": ["Scuba Diving", "스쿠버다이빙", "潜水", "潛水"],
  "enumdesc-interests-scubaDiving": ["Scuba Diving", "스쿠버다이빙", "潜水", "潛水"],
  "enum-interests-puppy": ["Puppy", "강아지", "小狗", "小狗"],
  "enumdesc-interests-puppy": ["Puppy", "강아지", "小狗", "小狗"],
  "enum-interests-financialPlanning": ["Financial Planning", "재테크", "理财", "理財"],
  "enumdesc-interests-financialPlanning": ["Financial Planning", "재테크", "理财", "理財"],
  "enum-interests-aquarium": ["Aquarium", "아쿠아리움", "水族馆", "水族館"],
  "enumdesc-interests-aquarium": ["Aquarium", "아쿠아리움", "水族馆", "水族館"],
  "enum-interests-leagueOfLegends": ["League of Legends", "리그오브레전드", "英雄联盟", "英雄聯盟"],
  "enumdesc-interests-leagueOfLegends": ["League of Legends", "리그오브레전드", "英雄联盟", "英雄聯盟"],
  "enum-interests-pubg": ["PUBG", "배틀그라운드", "绝地求生", "絕地求生"],
  "enumdesc-interests-pubg": ["PUBG", "배틀그라운드", "绝地求生", "絕地求生"],
  "enum-interests-amongUs": ["Among Us", "어몽어스", "Among Us", "Among Us"],
  "enumdesc-interests-amongUs": ["Among Us", "어몽어스", "Among Us", "Among Us"],
} as const;
