export const languagesDict = {
  "enum-language-mandarinChinese": ["Mandarin Chinese", "중국어(푸톈화)"],
  "enumdesc-language-mandarinChinese": ["Mandarin Chinese", "중국어(푸톈화)"],
  "enum-language-english": ["English", "영어"],
  "enumdesc-language-english": ["English", "영어"],
  "enum-language-hindi": ["Hindi", "힌디어"],
  "enumdesc-language-hindi": ["Hindi", "힌디어"],
  "enum-language-spanish": ["Spanish", "스페인어"],
  "enumdesc-language-spanish": ["Spanish", "스페인어"],
  "enum-language-bengali": ["Bengali", "벵골어"],
  "enumdesc-language-bengali": ["Bengali", "벵골어"],
  "enum-language-portuguese": ["Portuguese", "포르투갈어"],
  "enumdesc-language-portuguese": ["Portuguese", "포르투갈어"],
  "enum-language-russian": ["Russian", "러시아어"],
  "enumdesc-language-russian": ["Russian", "러시아어"],
  "enum-language-japanese": ["Japanese", "일본어"],
  "enumdesc-language-japanese": ["Japanese", "일본어"],
  "enum-language-westernPunjabi": ["Western Punjabi", "서부 펀자브어"],
  "enumdesc-language-westernPunjabi": ["Western Punjabi", "서부 펀자브어"],
  "enum-language-marathi": ["Marathi", "마라티어"],
  "enumdesc-language-marathi": ["Marathi", "마라티어"],
  "enum-language-telugu": ["Telugu", "텔루구어"],
  "enumdesc-language-telugu": ["Telugu", "텔루구어"],
  "enum-language-wuChinese": ["Wu Chinese", "우어"],
  "enumdesc-language-wuChinese": ["Wu Chinese", "우어"],
  "enum-language-turkish": ["Turkish", "터키어"],
  "enumdesc-language-turkish": ["Turkish", "터키어"],
  "enum-language-korean": ["Korean", "한국어"],
  "enumdesc-language-korean": ["Korean", "한국어"],
  "enum-language-french": ["French", "프랑스어"],
  "enumdesc-language-french": ["French", "프랑스어"],
  "enum-language-german": ["German", "독일어"],
  "enumdesc-language-german": ["German", "독일어"],
  "enum-language-vietnamese": ["Vietnamese", "베트남어"],
  "enumdesc-language-vietnamese": ["Vietnamese", "베트남어"],
  "enum-language-tamil": ["Tamil", "타밀어"],
  "enumdesc-language-tamil": ["Tamil", "타밀어"],
  "enum-language-yueChinese": ["Yue Chinese", "광둥어"],
  "enumdesc-language-yueChinese": ["Yue Chinese", "광둥어"],
  "enum-language-urdu": ["Urdu", "우르두어"],
  "enumdesc-language-urdu": ["Urdu", "우르두어"],
  "enum-language-javanese": ["Javanese", "자바어"],
  "enumdesc-language-javanese": ["Javanese", "자바어"],
  "enum-language-italian": ["Italian", "이탈리아어"],
  "enumdesc-language-italian": ["Italian", "이탈리아어"],
  "enum-language-egyptianArabic": ["Egyptian Arabic", "이집트 아랍어"],
  "enumdesc-language-egyptianArabic": ["Egyptian Arabic", "이집트 아랍어"],
  "enum-language-gujarati": ["Gujarati", "구자라트어"],
  "enumdesc-language-gujarati": ["Gujarati", "구자라트어"],
  "enum-language-iranianPersian": ["Iranian Persian", "이란 페르시아어"],
  "enumdesc-language-iranianPersian": ["Iranian Persian", "이란 페르시아어"],
  "enum-language-bhojpuri": ["Bhojpuri", "보지푸리어"],
  "enumdesc-language-bhojpuri": ["Bhojpuri", "보지푸리어"],
  "enum-language-minNanChinese": ["Min Nan Chinese", "민난어"],
  "enumdesc-language-minNanChinese": ["Min Nan Chinese", "민난어"],
  "enum-language-hakkaChinese": ["Hakka Chinese", "학가어"],
  "enumdesc-language-hakkaChinese": ["Hakka Chinese", "학가어"],
  "enum-language-jinChinese": ["Jin Chinese", "진어"],
  "enumdesc-language-jinChinese": ["Jin Chinese", "진어"],
  "enum-language-hausa": ["Hausa", "하우사어"],
  "enumdesc-language-hausa": ["Hausa", "하우사어"],
  "enum-language-kannada": ["Kannada", "칸나다어"],
  "enumdesc-language-kannada": ["Kannada", "칸나다어"],
  "enum-language-indonesian": ["Indonesian", "인도네시아어"],
  "enumdesc-language-indonesian": ["Indonesian", "인도네시아어"],
  "enum-language-polish": ["Polish", "폴란드어"],
  "enumdesc-language-polish": ["Polish", "폴란드어"],
  "enum-language-yoruba": ["Yoruba", "요루바어"],
  "enumdesc-language-yoruba": ["Yoruba", "요루바어"],
  "enum-language-xiangChinese": ["Xiang Chinese", "향어"],
  "enumdesc-language-xiangChinese": ["Xiang Chinese", "향어"],
  "enum-language-malayalam": ["Malayalam", "말라얄람어"],
  "enumdesc-language-malayalam": ["Malayalam", "말라얄람어"],
  "enum-language-odia": ["Odia", "오리야어"],
  "enumdesc-language-odia": ["Odia", "오리야어"],
  "enum-language-maithili": ["Maithili", "마이틸리어"],
  "enumdesc-language-maithili": ["Maithili", "마이틸리어"],
  "enum-language-burmese": ["Burmese", "버마어"],
  "enumdesc-language-burmese": ["Burmese", "버마어"],
  "enum-language-easternPunjabi": ["Eastern Punjabi", "동부 펀자브어"],
  "enumdesc-language-easternPunjabi": ["Eastern Punjabi", "동부 펀자브어"],
  "enum-language-sunda": ["Sunda", "순다어"],
  "enumdesc-language-sunda": ["Sunda", "순다어"],
  "enum-language-sudaneseArabic": ["Sudanese Arabic", "수단 아랍어"],
  "enumdesc-language-sudaneseArabic": ["Sudanese Arabic", "수단 아랍어"],
  "enum-language-algerianArabic": ["Algerian Arabic", "알제리 아랍어"],
  "enumdesc-language-algerianArabic": ["Algerian Arabic", "알제리 아랍어"],
  "enum-language-moroccanArabic": ["Moroccan Arabic", "모로코 아랍어"],
  "enumdesc-language-moroccanArabic": ["Moroccan Arabic", "모로코 아랍어"],
  "enum-language-ukrainian": ["Ukrainian", "우크라이나어"],
  "enumdesc-language-ukrainian": ["Ukrainian", "우크라이나어"],
  "enum-language-igbo": ["Igbo", "이그보어"],
  "enumdesc-language-igbo": ["Igbo", "이그보어"],
  "enum-language-northernUzbek": ["Northern Uzbek", "북부 우즈베크어"],
  "enumdesc-language-northernUzbek": ["Northern Uzbek", "북부 우즈베크어"],
  "enum-language-sindhi": ["Sindhi", "신디어"],
  "enumdesc-language-sindhi": ["Sindhi", "신디어"],
  "enum-language-northLevantineArabic": ["North Levantine Arabic", "북부 레반트 아랍어"],
  "enumdesc-language-northLevantineArabic": ["North Levantine Arabic", "북부 레반트 아랍어"],
  "enum-language-romanian": ["Romanian", "루마니아어"],
  "enumdesc-language-romanian": ["Romanian", "루마니아어"],
  "enum-language-tagalog": ["Tagalog", "타갈로그어"],
  "enumdesc-language-tagalog": ["Tagalog", "타갈로그어"],
  "enum-language-dutch": ["Dutch", "네덜란드어"],
  "enumdesc-language-dutch": ["Dutch", "네덜란드어"],
  "enum-language-saIdiArabic": ["Sa'idi Arabic", "사이디 아랍어"],
  "enumdesc-language-saIdiArabic": ["Sa'idi Arabic", "사이디 아랍어"],
  "enum-language-ganChinese": ["Gan Chinese", "간어"],
  "enumdesc-language-ganChinese": ["Gan Chinese", "간어"],
  "enum-language-amharic": ["Amharic", "암하라어"],
  "enumdesc-language-amharic": ["Amharic", "암하라어"],
  "enum-language-northernPashto": ["Northern Pashto", "북부 파슈토어"],
  "enumdesc-language-northernPashto": ["Northern Pashto", "북부 파슈토어"],
  "enum-language-magahi": ["Magahi", "마가히어"],
  "enumdesc-language-magahi": ["Magahi", "마가히어"],
  "enum-language-thai": ["Thai", "태국어"],
  "enumdesc-language-thai": ["Thai", "태국어"],
  "enum-language-saraiki": ["Saraiki", "사라키어"],
  "enumdesc-language-saraiki": ["Saraiki", "사라키어"],
  "enum-language-khmer": ["Khmer", "캄보디아어"],
  "enumdesc-language-khmer": ["Khmer", "캄보디아어"],
  "enum-language-chhattisgarhi": ["Chhattisgarhi", "차티스가리어"],
  "enumdesc-language-chhattisgarhi": ["Chhattisgarhi", "차티스가리어"],
  "enum-language-somali": ["Somali", "소말리어"],
  "enumdesc-language-somali": ["Somali", "소말리어"],
  "enum-language-malaysian": ["Malaysian", "말레이시아어"],
  "enumdesc-language-malaysian": ["Malaysian", "말레이시아어"],
  "enum-language-cebuano": ["Cebuano", "세부아노어"],
  "enumdesc-language-cebuano": ["Cebuano", "세부아노어"],
  "enum-language-nepali": ["Nepali", "네팔어"],
  "enumdesc-language-nepali": ["Nepali", "네팔어"],
  "enum-language-mesopotamianArabic": ["Mesopotamian Arabic", "메소포타미아 아랍어"],
  "enumdesc-language-mesopotamianArabic": ["Mesopotamian Arabic", "메소포타미아 아랍어"],
  "enum-language-assamese": ["Assamese", "아샘어"],
  "enumdesc-language-assamese": ["Assamese", "아샘어"],
  "enum-language-sinhalese": ["Sinhalese", "싱할라어"],
  "enumdesc-language-sinhalese": ["Sinhalese", "싱할라어"],
  "enum-language-northernKurdish": ["Northern Kurdish", "북부 쿠르드어"],
  "enumdesc-language-northernKurdish": ["Northern Kurdish", "북부 쿠르드어"],
  "enum-language-hejaziArabic": ["Hejazi Arabic", "헤자지 아랍어"],
  "enumdesc-language-hejaziArabic": ["Hejazi Arabic", "헤자지 아랍어"],
  "enum-language-nigerianFulfulde": ["Nigerian Fulfulde", "니제리아 풀풀데어"],
  "enumdesc-language-nigerianFulfulde": ["Nigerian Fulfulde", "니제리아 풀풀데어"],
  "enum-language-bavarian": ["Bavarian", "바바리아어"],
  "enumdesc-language-bavarian": ["Bavarian", "바바리아어"],
  "enum-language-southAzerbaijani": ["South Azerbaijani", "남아제르바이잔어"],
  "enumdesc-language-southAzerbaijani": ["South Azerbaijani", "남아제르바이잔어"],
  "enum-language-greek": ["Greek", "그리스어"],
  "enumdesc-language-greek": ["Greek", "그리스어"],
  "enum-language-chittagonian": ["Chittagonian", "치타곤어"],
  "enumdesc-language-chittagonian": ["Chittagonian", "치타곤어"],
  "enum-language-kazakh": ["Kazakh", "카자흐어"],
  "enumdesc-language-kazakh": ["Kazakh", "카자흐어"],
  "enum-language-deccan": ["Deccan", "데칸어"],
  "enumdesc-language-deccan": ["Deccan", "데칸어"],
  "enum-language-hungarian": ["Hungarian", "헝가리어"],
  "enumdesc-language-hungarian": ["Hungarian", "헝가리어"],
  "enum-language-kinyarwanda": ["Kinyarwanda", "키냐루완다어"],
  "enumdesc-language-kinyarwanda": ["Kinyarwanda", "키냐루완다어"],
  "enum-language-zulu": ["Zulu", "줄루어"],
  "enumdesc-language-zulu": ["Zulu", "줄루어"],
  "enum-language-southLevantineArabic": ["South Levantine Arabic", "남부 레반트 아랍어"],
  "enumdesc-language-southLevantineArabic": ["South Levantine Arabic", "남부 레반트 아랍어"],
  "enum-language-tunisianArabic": ["Tunisian Arabic", "튀니지 아랍어"],
  "enumdesc-language-tunisianArabic": ["Tunisian Arabic", "튀니지 아랍어"],
  "enum-language-sanaaniSpokenArabic": ["Sanaani Spoken Arabic", "사나아니 방언 아랍어"],
  "enumdesc-language-sanaaniSpokenArabic": ["Sanaani Spoken Arabic", "사나아니 방언 아랍어"],
  "enum-language-minBeiChinese": ["Min Bei Chinese", "북부 민베이어"],
  "enumdesc-language-minBeiChinese": ["Min Bei Chinese", "북부 민베이어"],
  "enum-language-southernPashto": ["Southern Pashto", "남부 파슈토어"],
  "enumdesc-language-southernPashto": ["Southern Pashto", "남부 파슈토어"],
  "enum-language-rundi": ["Rundi", "룬디어"],
  "enumdesc-language-rundi": ["Rundi", "룬디어"],
  "enum-language-czech": ["Czech", "체코어"],
  "enumdesc-language-czech": ["Czech", "체코어"],
  "enum-language-taIzzi-AdeniArabic": ["Ta'izzi-Adeni Arabic", "타이지-아데니 아랍어"],
  "enumdesc-language-taIzzi-AdeniArabic": ["Ta'izzi-Adeni Arabic", "타이지-아데니 아랍어"],
  "enum-language-uyghur": ["Uyghur", "위구르어"],
  "enumdesc-language-uyghur": ["Uyghur", "위구르어"],
  "enum-language-minDongChinese": ["Min Dong Chinese", "동부 민동어"],
  "enumdesc-language-minDongChinese": ["Min Dong Chinese", "동부 민동어"],
  "enum-language-sylheti": ["Sylheti", "실헤티어"],
  "enumdesc-language-sylheti": ["Sylheti", "실헤티어"],
} as const;
