{{- $namespaceParts := split "-" .Release.Namespace }}
{{- $branch := index $namespaceParts "_1" }}
{{- $config := index .Values $branch }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-federation-deployment
  namespace: {{ .Values.appName }}-{{ $branch }}
  labels:
    app: backend-federation
spec:
  replicas: {{ $config.backend.federation.replicas }}
  selector:
    matchLabels:
      app: backend-federation
  template:
    metadata:
      labels:
        app: backend-federation
    spec:
      containers:
        - name: backend-federation
          image: registry.akamir.com/akamir/{{ .Values.appName }}/backend:{{ $branch }}-live
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: {{ $config.backend.federation.resources.requests.memory }}
              cpu: {{ $config.backend.federation.resources.requests.cpu }}
            limits:
              memory: {{ $config.backend.federation.resources.limits.memory }}
              cpu: {{ $config.backend.federation.resources.limits.cpu }}
          env:
            - name: NEXT_PUBLIC_ENV
              value: {{ $branch }}
            - name: SERVER_MODE
              value: federation
      imagePullSecrets:
        - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-batch-deployment
  namespace: {{ .Values.appName }}-{{ $branch }}
  labels:
    app: backend-batch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-batch
  template:
    metadata:
      labels:
        app: backend-batch
    spec:
      containers:
        - name: backend-batch
          image: registry.akamir.com/akamir/{{ .Values.appName }}/backend:{{ $branch }}-live
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: {{ $config.backend.batch.resources.requests.memory }}
              cpu: {{ $config.backend.batch.resources.requests.cpu }}
            limits:
              memory: {{ $config.backend.batch.resources.limits.memory }}
              cpu: {{ $config.backend.batch.resources.limits.cpu }}
          env:
            - name: NEXT_PUBLIC_ENV
              value: {{ $branch }}
            - name: SERVER_MODE
              value: batch
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: {{ .Values.appName }}-{{ $branch }}
spec:
  selector:
    app: backend-federation
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
