{{- $namespaceParts := split "-" .Release.Namespace }}
{{- $branch := index $namespaceParts "_1" }}
{{- $config := index .Values $branch }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: meili
  namespace: {{ .Values.appName }}-{{ $branch }}
  labels:
    app.kubernetes.io/name: meilisearch
    app.kubernetes.io/instance: meilisearch
    app.kubernetes.io/version: "v1.10.0"
    app.kubernetes.io/component: search-engine
    app.kubernetes.io/part-of: meilisearch
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: meili-cfg
  namespace: {{ .Values.appName }}-{{ $branch }}
  labels:
    app.kubernetes.io/name: meilisearch
    app.kubernetes.io/instance: meilisearch
    app.kubernetes.io/version: "v1.10.0"
    app.kubernetes.io/component: search-engine
    app.kubernetes.io/part-of: meilisearch
data:
  MEILI_ENV: "development"
  MEILI_NO_ANALYTICS: "true"
  MEILI_MASTER_KEY: meilisearch-key-{{ .Values.appName }}-{{ $branch }}
---
apiVersion: v1
kind: Service
metadata:
  name: meili-svc
  namespace: {{ .Values.appName }}-{{ $branch }}
  labels:
    app.kubernetes.io/name: meilisearch
    app.kubernetes.io/instance: meilisearch
    app.kubernetes.io/version: "v1.10.0"
    app.kubernetes.io/component: search-engine
    app.kubernetes.io/part-of: meilisearch
spec:
  type: ClusterIP
  ports:
    - port: 7700
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: meilisearch
    app.kubernetes.io/instance: meilisearch
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: meili
  namespace: {{ .Values.appName }}-{{ $branch }}
  labels:
    app.kubernetes.io/name: meilisearch
    app.kubernetes.io/instance: meilisearch
    app.kubernetes.io/version: "v1.10.0"
    app.kubernetes.io/component: search-engine
    app.kubernetes.io/part-of: meilisearch
spec:
  replicas: 1
  serviceName: meili-svc
  selector:
    matchLabels:
      app.kubernetes.io/name: meilisearch
      app.kubernetes.io/instance: meilisearch
  template:
    metadata:
      labels:
        app.kubernetes.io/name: meilisearch
        app.kubernetes.io/instance: meilisearch
        app.kubernetes.io/version: "v1.10.0"
        app.kubernetes.io/component: search-engine
        app.kubernetes.io/part-of: meilisearch
      annotations:
        checksum/config: 8f77a9c4595d90c6a6ddab98f1b9668b3a7922533e360f47f6e58c106e936729
    spec:
      serviceAccountName: meili
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
      volumes:
        - name: tmp
          emptyDir: {}
        - name: data
          persistentVolumeClaim:
            claimName: data-volume-meili-0
      containers:
        - name: meili
          image: "getmeili/meilisearch:v1.10.0"
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: data
              mountPath: /meili_data
          envFrom:
          - configMapRef:
              name: meili-cfg
          ports:
            - name: http
              containerPort: 7700
              protocol: TCP
          startupProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 1
            initialDelaySeconds: 1
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            initialDelaySeconds: 0
          readinessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            initialDelaySeconds: 0
          resources:
            limits:
              cpu: {{ $config.meili.resources.limits.cpu }}
              memory: {{ $config.meili.resources.limits.memory }}
            requests:
              cpu: {{ $config.meili.resources.requests.cpu }}
              memory: {{ $config.meili.resources.requests.memory }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-volume-meili-0
  namespace: {{ .Values.appName }}-{{ $branch }}
  labels:
    app.kubernetes.io/name: meilisearch
    app.kubernetes.io/instance: meilisearch
    app.kubernetes.io/version: "v1.10.0"
    app.kubernetes.io/component: search-engine
    app.kubernetes.io/part-of: meilisearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $config.meili.storage.data }}
  selector:
    matchLabels:
      app.kubernetes.io/name: meilisearch
      app.kubernetes.io/instance: meilisearch
  storageClassName: default
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $.Values.appName }}-{{ $branch }}-meili-data-volume-0
  labels:
    namespace: {{ $.Values.appName }}-{{ $branch }}
    app.kubernetes.io/name: meilisearch
    app.kubernetes.io/instance: meilisearch
    app.kubernetes.io/version: "v1.10.0"
    app.kubernetes.io/component: search-engine
    app.kubernetes.io/part-of: meilisearch
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ $config.meili.storage.data }}
  hostPath:
    path: /root/kubernetes/{{ $.Values.appName }}-{{ $branch }}/meili/data-0
    type: ""
  persistentVolumeReclaimPolicy: Delete
  storageClassName: default
  volumeMode: Filesystem
